[package]
name = "sita"
version = "1.0.0"
authors = ["Joel Parker Henderson <joel@joelparkerhenderson.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ammonia = "3.1.1" # HTML Sanitization
assertables = "3.2.1" # Runtime reliability checking macros
clap = { version = "3.0.0-beta.2", features = ["regex", "yaml", "wrap_help"] } # Command Line Argument Parser
confy = "0.4.0" # Boilerplate-free configuration management
env_logger = "0.8.3" # A logger that can be configured via environment variables
error-chain = "0.12.4" # Consistent error handling
indoc = "1.0.3" # Indented document literals
lazy_static = "1.4.0" # A macro for declaring lazily evaluated statics
liquid = "0.22.0" #  Liquid templating language for Rust
log = "0.4.0" # A Rust library providing a lightweight logging facade
maplit = "1.0.2" # Macros for container literals with specific type
minidom = "0.13.0" # A small, simple DOM implementation on top of quick-xml
once_cell = "1.7.2" # Single assignment cells and lazy values
pulldown-cmark = "0.8.0" #  A pull parser for CommonMark
regex = "1.4.5" # Regular expressions parser, compiler, and executer
quick-xml = "0.22.0" # High-performance XML reader and writer
serde = { version = "1.0", features = ["derive"] } # Generic serialize/deserialize framework
tera = "1.10.0" # Template engine based on Jinja2/Django templates
yaml-rust = "0.4.5" # YAML parser
json = "0.12.4" # JSON parser
toml = "0.5.8" # TOML encoder/decoder
url = "2.2.2" # URL library for Rust, based on the WHATWG URL Standard
serde_json = "1.0.64" # JSON serialize/deserialize
serde_yaml = "0.8.17" # YAML serialize/deserialize
