[package]
name = "sita"
version = "1.0.0"
authors = ["Joel Parker Henderson <joel@joelparkerhenderson.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ammonia = "3.1.1" # HTML Sanitization
assertables = "3.2.1" # Runtime reliability checking macros
base64 = "*" # Encodes and decodes base64 as bytes or utf8
bytes = "*" # Types and traits for working with bytes
clap = { version = "3.0.0-a", features = ["regex", "yaml", "wrap_help"] } # Command Line Argument Parser
confy = "0.4.0" # Boilerplate-free configuration management
env_logger = "0.8.3" # A logger that can be configured via environment variables
error-chain = "0.12.4" # Consistent error handling
glob = "0.3.0" # Support for matching file paths against Unix shell style patterns
handlebars = { version = "4.0.1", features = ["script_helper"] } # Template engine based on JavaScript Handlebars templates
httpdate = "*" # HTTP date parsing and formatting
indoc = "1.0.3" # Indented document literals
ipnet = "*" # Types and methods for working with IPv4 and IPv6 network addresses
json = "0.12.4" # JSON parser
lazy_static = "1.4.0" # A macro for declaring lazily evaluated statics
liquid = "0.22.0" #  Liquid templating language for Rust
log = "0.4.0" # A Rust library providing a lightweight logging facade
loupe = "0.1" # Analyse and profile Rust code memory usage
maplit = "1.0.2" # Macros for container literals with specific type
matches = "*" # A macro to evaluate if an expression matches a pattern
mime = "*" # Strongly Typed Mimes
minidom = "0.13.0" # A small, simple DOM implementation on top of quick-xml
once_cell = "1.7.2" # Single assignment cells and lazy values
pulldown-cmark = "0.8.0" #  A pull parser for CommonMark
regex = "1.4.5" # Regular expressions parser, compiler, and executer
rhai = "1.0.4" # Embedded scripting for Rust
quick-xml = "0.22.0" # High-performance XML reader and writer
serde = { version = "1.0", features = ["derive"] } # Generic serialize/deserialize framework
serde_json = "1.0.64" # JSON serialize/deserialize
serde_yaml = "0.8.17" # YAML serialize/deserialize
strsim = "*" # String similarity metrics
tera = "1.10.0" # Template engine based on Jinja2/Django templates
toml = { version = "0.5.8", features = ["preserve_order"] } # TOML encoder/decoder
unicode-segmentation = "1.7.1" #  Iterators which split strings on graphemes, words, etc.
url = "2.2.2" # URL library for Rust, based on the WHATWG URL Standard
version_check = "*" # Check the version of the installed/running rustc
yaml-rust = "0.4.5" # YAML parser
